import config from 'config/index'

import cryptoIcons from 'assets/crypto-icons-stack.svg'
import rocketPoolETHIcons from 'assets/tokens/RocketPoolETH.png'
import ustIcons from 'assets/tokens/ust.png'
import ust_whIcons from 'assets/tokens/UST_wh.png'
import ust_utIcons from 'assets/tokens/ust.png'
import pusdIcons from 'assets/tokens/PUSD.jpeg'

export const PRICE_API = [
  { tokens: ['steth'], api: 'https://stats.curve.fi/raw-stats/apys.json' },
  { tokens: ['triCrypto2', 'crveth', 'cvxeth'], api: 'https://stats.curve.fi/raw-stats-crypto/apys.json' },
  {
    tokens: ['frax', 'alusd', 'mim', 'cvxcrv', 'AlETH', 'mim-ust', 'ust-wormhole'],
    api: 'https://api.curve.fi/api/getFactoryAPYs?version=2',
    addrs: config.convexVaultPool,
  },
]

export const VAULT_LIST = [
  {
    logo: `${cryptoIcons}#steth`,
    id: 0,
    name: 'steth',
    nameShow: 'Curve stETH pool',
    apy: 0,
    stakeTokenSymbol: 'stethCRV',
    tvlPriceTokenId: 'curveLP-steth',
    stakeTokenContractAddress: config.convexVaultPool.steth,
    stakeTokenDecimals: 18,
    rewardTokenSymbol: 'CTR',
    rewardTokenDecimals: 18,
    zapTokens: [
      {
        symbol: 'stethCRV',
        icon: 'steth',
        address: config.convexVaultPool.steth,
        needZap: false,
        isLp: true,
      },
      {
        symbol: 'stETH',
        icon: 'steth',
        address: config.tokens.steth,
        needZap: true,
      },
      {
        symbol: 'ETH',
        icon: 'eth',
        address: config.tokens.eth,
        needZap: true,
      },
      {
        symbol: 'WETH',
        icon: 'weth',
        address: config.tokens.weth,
        needZap: true,
      },
      {
        symbol: 'USDC',
        icon: 'usdc',
        decimals: 6,
        address: config.tokens.usdc,
        needZap: true,
      },
    ],
  },
  {
    logo: `${cryptoIcons}#frax`,
    id: 1,
    name: 'frax',
    nameShow: 'Curve frax pool',
    apy: 0,
    stakeTokenSymbol: 'fraxCrv',
    tvlPriceTokenId: 'curveLP-frax',
    stakeTokenContractAddress: config.convexVaultPool.frax,
    stakeTokenDecimals: 18,
    rewardTokenSymbol: 'CTR',
    rewardTokenDecimals: 18,
    zapTokens: [
      {
        symbol: 'fraxCrv',
        icon: 'frax',
        address: config.convexVaultPool.frax,
        needZap: false,
        isLp: true,
      },
      {
        symbol: 'frax',
        icon: 'frax',
        address: config.tokens.frax,
        needZap: true,
      },
      {
        symbol: 'crv3pool',
        icon: '3pool',
        address: config.convexVaultPool.crv3pool,
        needZap: true,
        isLp: true,
      },
      {
        symbol: 'USDT',
        icon: 'usdt',
        decimals: 6,
        address: config.tokens.usdt,
        needZap: true,
      },
      {
        symbol: 'USDC',
        icon: 'usdc',
        decimals: 6,
        address: config.tokens.usdc,
        needZap: true,
      },
      {
        symbol: 'ETH',
        icon: 'eth',
        address: config.tokens.eth,
        needZap: true,
      },
      {
        symbol: 'DAI',
        icon: 'dai',
        address: config.tokens.dai,
        needZap: true,
      },
      {
        symbol: 'WETH',
        icon: 'weth',
        address: config.tokens.weth,
        needZap: true,
      },
    ],
  },
  {
    logo: `${cryptoIcons}#tricrypto2`,
    id: 2,
    name: 'tricrypto2',
    nameShow: 'Curve tricrypto2 pool',
    apy: 0,
    stakeTokenSymbol: '3CrvCrypto2',
    tvlPriceTokenId: 'curveLP-tricrypto2',
    stakeTokenContractAddress: config.convexVaultPool.tricrypto2,
    stakeTokenDecimals: 18,
    rewardTokenSymbol: 'CTR',
    rewardTokenDecimals: 18,
    zapTokens: [
      {
        symbol: '3CrvCrypto2',
        icon: 'tricrypto2',
        address: config.convexVaultPool.tricrypto2,
        needZap: false,
        isLp: true,
      },
      {
        symbol: 'WBTC',
        icon: 'wbtc',
        address: config.tokens.wbtc,
        decimals: 8,
        needZap: true,
      },
      {
        symbol: 'ETH',
        icon: 'eth',
        address: config.tokens.eth,
        needZap: true,
      },
      {
        symbol: 'WETH',
        icon: 'weth',
        address: config.tokens.weth,
        needZap: true,
      },
      {
        symbol: 'USDT',
        icon: 'usdt',
        decimals: 6,
        address: config.tokens.usdt,
        needZap: true,
      },
      {
        symbol: 'USDC',
        icon: 'usdc',
        decimals: 6,
        address: config.tokens.usdc,
        needZap: true,
      },
    ],
  },
  {
    logo: `${cryptoIcons}#crv`,
    id: 3,
    apy: 0,
    name: 'cvxcrv',
    nameShow: 'Curve cvxcrv pool',
    stakeTokenSymbol: 'cvxcrvCrv',
    tvlPriceTokenId: 'curveLP-cvxcrv',
    stakeTokenContractAddress: config.convexVaultPool.cvxcrv,
    stakeTokenDecimals: 18,
    rewardTokenSymbol: 'CTR',
    rewardTokenDecimals: 18,
    zapTokens: [
      {
        symbol: 'cvxcrvCrv',
        icon: 'crv',
        address: config.convexVaultPool.cvxcrv,
        needZap: false,
        isLp: true,
      },
      {
        symbol: 'CRV',
        icon: 'crv',
        address: config.tokens.crv,
        needZap: true,
      },
      {
        symbol: 'cvxCRV',
        icon: 'crv',
        address: config.tokens.cvxcrv,
        needZap: true,
      },
      {
        symbol: 'ETH',
        icon: 'eth',
        address: config.tokens.eth,
        needZap: true,
      },
      {
        symbol: 'WETH',
        icon: 'weth',
        address: config.tokens.weth,
        needZap: true,
      },
      {
        symbol: 'USDC',
        icon: 'usdc',
        decimals: 6,
        address: config.tokens.usdc,
        needZap: true,
      },
    ],
  },
  {
    logo: `${cryptoIcons}#crv`,
    id: 4,
    name: 'crveth',
    nameShow: 'Curve crveth pool',
    apy: 0,
    stakeTokenSymbol: 'crvethCrv',
    tvlPriceTokenId: 'curveLP-crveth',
    stakeTokenContractAddress: config.convexVaultPool.crveth,
    stakeTokenDecimals: 18,
    rewardTokenSymbol: 'CTR',
    rewardTokenDecimals: 18,
    zapTokens: [
      {
        symbol: 'crvethCrv',
        icon: 'crv',
        address: config.convexVaultPool.crveth,
        isLp: true,
        needZap: false,
      },
      {
        symbol: 'CRV',
        icon: 'crv',
        address: config.tokens.crv,
        needZap: true,
      },
      {
        symbol: 'ETH',
        icon: 'eth',
        address: config.tokens.eth,
        needZap: true,
      },
      {
        symbol: 'WETH',
        icon: 'weth',
        address: config.tokens.weth,
        needZap: true,
      },
      {
        symbol: 'USDC',
        icon: 'usdc',
        decimals: 6,
        address: config.tokens.usdc,
        needZap: true,
      },
    ],
  },
  {
    logo: `${cryptoIcons}#cvx`,
    id: 5,
    name: 'cvxeth',
    nameShow: 'Curve cvxeth pool',
    apy: 0,
    stakeTokenSymbol: 'cvxethCrv',
    tvlPriceTokenId: 'curveLP-cvxeth',
    stakeTokenContractAddress: config.convexVaultPool.cvxeth,
    stakeTokenDecimals: 18,
    rewardTokenSymbol: 'CTR',
    rewardTokenDecimals: 18,
    zapTokens: [
      {
        symbol: 'cvxethCrv',
        icon: 'cvx',
        address: config.convexVaultPool.cvxeth,
        isLp: true,
        needZap: false,
      },
      {
        symbol: 'CVX',
        icon: 'cvx',
        address: config.tokens.cvx,
        needZap: true,
      },
      {
        symbol: 'ETH',
        icon: 'eth',
        address: config.tokens.eth,
        needZap: true,
      },
      {
        symbol: 'WETH',
        icon: 'weth',
        address: config.tokens.weth,
        needZap: true,
      },
      {
        symbol: 'USDC',
        icon: 'usdc',
        decimals: 6,
        address: config.tokens.usdc,
        needZap: true,
      },
    ],
  },

  {
    logo: `${cryptoIcons}#fxs`,
    id: 6,
    apy: 0,
    name: 'cvxfxs',
    nameShow: 'Curve cvxfxs pool',
    stakeTokenSymbol: 'cvxfxsCrv',
    tvlPriceTokenId: 'curveLP-cvxfxs',
    stakeTokenContractAddress: config.convexVaultPool.cvxfxs,
    stakeTokenDecimals: 18,
    rewardTokenSymbol: 'CTR',
    rewardTokenDecimals: 18,
    site: 'convex',
    zapTokens: [
      {
        symbol: 'cvxfxsCrv',
        icon: 'fxs',
        address: config.convexVaultPool.cvxfxs,
        isLp: true,
        needZap: false,
      },
      {
        symbol: 'cvxFXS',
        icon: 'fxs',
        address: config.tokens.cvxfxs,
        needZap: true,
      },
      {
        symbol: 'FXS',
        icon: 'fxs',
        address: config.tokens.fxs,
        needZap: true,
      },
      {
        symbol: 'ETH',
        icon: 'eth',
        address: config.tokens.eth,
        needZap: true,
      },
      {
        symbol: 'WETH',
        icon: 'weth',
        address: config.tokens.weth,
        needZap: true,
      },
      {
        symbol: 'USDC',
        icon: 'usdc',
        decimals: 6,
        address: config.tokens.usdc,
        needZap: true,
      },
    ],
  },
  {
    logo: `${cryptoIcons}#3pool`,
    id: 7,
    apy: 0,
    name: '3pool',
    nameShow: 'Curve 3pool pool',
    stakeTokenSymbol: 'crv3pool',
    tvlPriceTokenId: 'curveLP-crv3pool',
    stakeTokenContractAddress: config.convexVaultPool.crv3pool,
    stakeTokenDecimals: 18,
    rewardTokenSymbol: 'CTR',
    rewardTokenDecimals: 18,
    site: 'convex',
    zapTokens: [
      {
        symbol: 'crv3pool',
        icon: '3pool',
        address: config.convexVaultPool.crv3pool,
        isLp: true,
        needZap: false,
      },
      {
        symbol: 'DAI',
        icon: 'dai',
        address: config.tokens.dai,
        needZap: true,
      },
      {
        symbol: 'USDC',
        icon: 'usdc',
        decimals: 6,
        address: config.tokens.usdc,
        needZap: true,
      },
      {
        symbol: 'USDT',
        icon: 'usdt',
        decimals: 6,
        address: config.tokens.usdt,
        needZap: true,
      },
      {
        symbol: 'ETH',
        icon: 'eth',
        address: config.tokens.eth,
        needZap: true,
      },
      {
        symbol: 'WETH',
        icon: 'weth',
        address: config.tokens.weth,
        needZap: true,
      },
    ],
  },

  {
    logo: ustIcons,
    id: 8,
    apy: 0,
    name: 'ust-wormhole',
    nameShow: 'Curve ust-wormhole pool',
    stakeTokenSymbol: 'ust-wormhole',
    tvlPriceTokenId: 'curveLP-ust-wormhole',
    stakeTokenContractAddress: config.convexVaultPool["ust-wormhole"],
    stakeTokenDecimals: 18,
    rewardTokenSymbol: 'CTR',
    rewardTokenDecimals: 18,
    site: 'convex',
    closeDeposit: true,
    isExpired: true,
    zapTokens: [
      {
        symbol: 'ust-wormhole',
        icon: ustIcons,
        address: config.convexVaultPool["ust-wormhole"],
        needZap: false,
        isLp: true,
      },
      // {
      //   symbol: 'UST (bridged by Wormhole)',
      //   icon: ust_whIcons,
      //   decimals: 6,
      //   address: config.tokens["UST(Wormhole)"],
      //   needZap: true,
      // },
      // {
      //   symbol: 'UST (bridged by Terra)',
      //   icon: ust_utIcons,
      //   address: config.tokens["UST(Terra)"],
      //   needZap: true,
      // },
      // {
      //   symbol: 'crv3pool',
      //   icon: '3pool',
      //   address: config.convexVaultPool.crv3pool,
      //   needZap: true,
      //   isLp: true,
      // },
      // {
      //   symbol: 'USDT',
      //   icon: 'usdt',
      //   decimals: 6,
      //   address: config.tokens.usdt,
      //   needZap: true,
      // },
      // {
      //   symbol: 'USDC',
      //   icon: 'usdc',
      //   decimals: 6,
      //   address: config.tokens.usdc,
      //   needZap: true,
      // },
      // {
      //   symbol: 'DAI',
      //   icon: 'dai',
      //   address: config.tokens.dai,
      //   needZap: true,
      // },
      // {
      //   symbol: 'ETH',
      //   icon: 'eth',
      //   address: config.tokens.eth,
      //   needZap: true,
      // },
      // {
      //   symbol: 'WETH',
      //   icon: 'weth',
      //   address: config.tokens.weth,
      //   needZap: true,
      // },
    ],
  },

  {
    logo: rocketPoolETHIcons,
    id: 9,
    apy: 0,
    name: 'RocketPoolETH',
    nameShow: 'Curve RocketPoolETH pool',
    stakeTokenSymbol: 'RocketPoolETH',
    tvlPriceTokenId: 'curveLP-rocketpooleth',
    stakeTokenContractAddress: config.convexVaultPool.rocketpooleth,
    stakeTokenDecimals: 18,
    rewardTokenSymbol: 'CTR',
    rewardTokenDecimals: 18,
    isShowEthApy: true,
    site: 'convex',
    zapTokens: [
      {
        symbol: 'RocketPoolETH',
        icon: rocketPoolETHIcons,
        address: config.convexVaultPool.rocketpooleth,
        needZap: false,
        isLp: true,
      },
      {
        symbol: 'ETH',
        icon: 'eth',
        address: config.tokens.eth,
        needZap: true,
      },
      {
        symbol: 'WETH',
        icon: 'weth',
        address: config.tokens.weth,
        needZap: true,
      },
      {
        symbol: 'stETH',
        icon: 'steth',
        address: config.tokens.steth,
        needZap: true,
      },
      {
        symbol: 'rETH',
        icon: rocketPoolETHIcons,
        address: config.tokens.reth,
        needZap: true,
      },
      {
        symbol: 'wstETH',
        icon: 'steth',
        address: config.tokens.wstETH,
        needZap: true,
      },
      {
        symbol: 'USDC',
        icon: 'usdc',
        decimals: 6,
        address: config.tokens.usdc,
        needZap: true,
      },
    ],
  },

  {
    logo: `${cryptoIcons}#renbtc`,
    id: 10,
    apy: 0,
    name: 'ren',
    nameShow: 'Curve ren pool',
    stakeTokenSymbol: 'renCrv',
    tvlPriceTokenId: 'curveLP-ren',
    stakeTokenContractAddress: config.convexVaultPool.ren,
    stakeTokenDecimals: 18,
    rewardTokenSymbol: 'CTR',
    rewardTokenDecimals: 18,
    isShowEthApy: false,
    site: 'convex',
    zapTokens: [
      {
        symbol: 'renCrv',
        icon: 'renbtc',
        address: config.convexVaultPool.ren,
        needZap: false,
        isLp: true,
      },
      {
        symbol: 'WBTC',
        icon: 'wbtc',
        address: config.tokens.wbtc,
        decimals: 8,
        needZap: true,
      },
      {
        symbol: 'ETH',
        icon: 'eth',
        address: config.tokens.eth,
        needZap: true,
      },
      {
        symbol: 'WETH',
        icon: 'weth',
        address: config.tokens.weth,
        needZap: true,
      },
      {
        symbol: 'renBTC',
        icon: 'renbtc',
        address: config.tokens.renBTC,
        decimals: 8,
        needZap: true,
      },

      {
        symbol: 'USDC',
        icon: 'usdc',
        decimals: 6,
        address: config.tokens.usdc,
        needZap: true,
      },
    ],
  },

  // {
  //   logo: pusdIcons,
  //   id: 11,
  //   apy: 0,
  //   name: 'pusd',
  //   nameShow: 'Curve pusd pool',
  //   stakeTokenSymbol: 'pusdCrv',
  //   tvlPriceTokenId: 'curveLP-pusd',
  //   stakeTokenContractAddress: config.convexVaultPool.pusd,
  //   stakeTokenDecimals: 18,
  //   rewardTokenSymbol: 'CTR',
  //   rewardTokenDecimals: 18,
  //   isShowEthApy: false,
  //   site: 'convex',
  //   zapTokens: [
  //     {
  //       symbol: 'pusdCrv',
  //       icon: pusdIcons,
  //       address: config.convexVaultPool.pusd,
  //       needZap: false,
  //       isLp: true,
  //     },
  //     {
  //       symbol: 'ETH',
  //       icon: 'eth',
  //       address: config.tokens.eth,
  //       needZap: true,
  //     },
  //     {
  //       symbol: 'WETH',
  //       icon: 'weth',
  //       address: config.tokens.weth,
  //       needZap: true,
  //     },
  //     {
  //       symbol: 'USDC',
  //       icon: 'usdc',
  //       decimals: 6,
  //       address: config.tokens.usdc,
  //       needZap: true,
  //     },
  //     {
  //       symbol: 'DAI',
  //       icon: 'dai',
  //       address: config.tokens.dai,
  //       needZap: true,
  //     },
  //     {
  //       symbol: 'USDT',
  //       icon: 'usdt',
  //       decimals: 6,
  //       address: config.tokens.usdt,
  //       needZap: true,
  //     },
  //     {
  //       symbol: 'crv3pool',
  //       icon: '3pool',
  //       address: config.convexVaultPool.crv3pool,
  //       needZap: true,
  //       isLp: true,
  //     },
  //     {
  //       symbol: 'PUSd',
  //       icon: pusdIcons,
  //       address: config.tokens.PUSd,
  //       needZap: true,
  //     },
  //   ],
  // }
]

export const VAULT_LIST_IFO = [
  {
    logo: `${cryptoIcons}#steth`,
    id: 0,
    name: 'steth',
    nameShow: 'Curve stETH pool',
    apy: 0,
    stakeTokenSymbol: 'stethCRV',
    tvlPriceTokenId: 'curveLP-steth',
    stakeTokenContractAddress: config.convexVaultPool.steth,
    stakeTokenDecimals: 18,
    rewardTokenSymbol: 'CTR',
    rewardTokenDecimals: 18,
    zapTokens: [
      {
        symbol: 'stethCRV',
        icon: 'steth',
        address: config.convexVaultPool.steth,
        needZap: false,
        isLp: true,
      },
      {
        symbol: 'stETH',
        icon: 'steth',
        address: config.tokens.steth,
        needZap: true,
      },
      {
        symbol: 'ETH',
        icon: 'eth',
        address: config.tokens.eth,
        needZap: true,
      },
      {
        symbol: 'WETH',
        icon: 'weth',
        address: config.tokens.weth,
        needZap: true,
      },
      {
        symbol: 'USDC',
        icon: 'usdc',
        decimals: 6,
        address: config.tokens.usdc,
        needZap: true,
      },
    ],
  },
  {
    logo: `${cryptoIcons}#frax`,
    id: 1,
    name: 'frax',
    nameShow: 'Curve frax pool',
    apy: 0,
    stakeTokenSymbol: 'fraxCrv',
    tvlPriceTokenId: 'curveLP-frax',
    stakeTokenContractAddress: config.convexVaultPool.frax,
    stakeTokenDecimals: 18,
    rewardTokenSymbol: 'CTR',
    rewardTokenDecimals: 18,
    zapTokens: [
      {
        symbol: 'fraxCrv',
        icon: 'frax',
        address: config.convexVaultPool.frax,
        needZap: false,
        isLp: true,
      },
      {
        symbol: 'frax',
        icon: 'frax',
        address: config.tokens.frax,
        needZap: true,
      },
      {
        symbol: 'crv3pool',
        icon: '3pool',
        address: config.convexVaultPool.crv3pool,
        needZap: true,
        isLp: true,
      },
      {
        symbol: 'USDT',
        icon: 'usdt',
        decimals: 6,
        address: config.tokens.usdt,
        needZap: true,
      },
      {
        symbol: 'USDC',
        icon: 'usdc',
        decimals: 6,
        address: config.tokens.usdc,
        needZap: true,
      },
      {
        symbol: 'ETH',
        icon: 'eth',
        address: config.tokens.eth,
        needZap: true,
      },
      {
        symbol: 'DAI',
        icon: 'dai',
        address: config.tokens.dai,
        needZap: true,
      },
      {
        symbol: 'WETH',
        icon: 'weth',
        address: config.tokens.weth,
        needZap: true,
      },
    ],
  },
  {
    logo: `${cryptoIcons}#tricrypto2`,
    id: 2,
    name: 'tricrypto2',
    nameShow: 'Curve tricrypto2 pool',
    apy: 0,
    stakeTokenSymbol: '3CrvCrypto2',
    tvlPriceTokenId: 'curveLP-tricrypto2',
    stakeTokenContractAddress: config.convexVaultPool.tricrypto2,
    stakeTokenDecimals: 18,
    rewardTokenSymbol: 'CTR',
    rewardTokenDecimals: 18,
    zapTokens: [
      {
        symbol: '3CrvCrypto2',
        icon: 'tricrypto2',
        address: config.convexVaultPool.tricrypto2,
        needZap: false,
        isLp: true,
      },
      {
        symbol: 'WBTC',
        icon: 'wbtc',
        address: config.tokens.wbtc,
        decimals: 8,
        needZap: true,
      },
      {
        symbol: 'ETH',
        icon: 'eth',
        address: config.tokens.eth,
        needZap: true,
      },
      {
        symbol: 'WETH',
        icon: 'weth',
        address: config.tokens.weth,
        needZap: true,
      },
      {
        symbol: 'USDT',
        icon: 'usdt',
        decimals: 6,
        address: config.tokens.usdt,
        needZap: true,
      },
      {
        symbol: 'USDC',
        icon: 'usdc',
        decimals: 6,
        address: config.tokens.usdc,
        needZap: true,
      },
    ],
  },
  {
    logo: `${cryptoIcons}#crv`,
    id: 3,
    apy: 0,
    name: 'cvxcrv',
    nameShow: 'Curve cvxcrv pool',
    stakeTokenSymbol: 'cvxcrvCrv',
    tvlPriceTokenId: 'curveLP-cvxcrv',
    stakeTokenContractAddress: config.convexVaultPool.cvxcrv,
    stakeTokenDecimals: 18,
    rewardTokenSymbol: 'CTR',
    rewardTokenDecimals: 18,
    zapTokens: [
      {
        symbol: 'cvxcrvCrv',
        icon: 'crv',
        address: config.convexVaultPool.cvxcrv,
        needZap: false,
        isLp: true,
      },
      {
        symbol: 'CRV',
        icon: 'crv',
        address: config.tokens.crv,
        needZap: true,
      },
      {
        symbol: 'cvxCRV',
        icon: 'crv',
        address: config.tokens.cvxcrv,
        needZap: true,
      },
      {
        symbol: 'ETH',
        icon: 'eth',
        address: config.tokens.eth,
        needZap: true,
      },
      {
        symbol: 'WETH',
        icon: 'weth',
        address: config.tokens.weth,
        needZap: true,
      },
      {
        symbol: 'USDC',
        icon: 'usdc',
        decimals: 6,
        address: config.tokens.usdc,
        needZap: true,
      },
    ],
  },
  {
    logo: `${cryptoIcons}#crv`,
    id: 4,
    name: 'crveth',
    nameShow: 'Curve crveth pool',
    apy: 0,
    stakeTokenSymbol: 'crvethCrv',
    tvlPriceTokenId: 'curveLP-crveth',
    stakeTokenContractAddress: config.convexVaultPool.crveth,
    stakeTokenDecimals: 18,
    rewardTokenSymbol: 'CTR',
    rewardTokenDecimals: 18,
    zapTokens: [
      {
        symbol: 'crvethCrv',
        icon: 'crv',
        address: config.convexVaultPool.crveth,
        isLp: true,
        needZap: false,
      },
      {
        symbol: 'CRV',
        icon: 'crv',
        address: config.tokens.crv,
        needZap: true,
      },
      {
        symbol: 'ETH',
        icon: 'eth',
        address: config.tokens.eth,
        needZap: true,
      },
      {
        symbol: 'WETH',
        icon: 'weth',
        address: config.tokens.weth,
        needZap: true,
      },
      {
        symbol: 'USDC',
        icon: 'usdc',
        decimals: 6,
        address: config.tokens.usdc,
        needZap: true,
      },
    ],
  },
]

export const LIQUIDITY_LIST_IFO = [
  {
    logo: `${cryptoIcons}#steth`,
    id: 0,
    name: 'Balancer CTR/aCrv LP',
    nameShow: 'Balancer CTR/aCrv LP',
    apy: 0,
    stakeTokenSymbol: 'CVX',
    tvlPriceTokenId: 'curveLP-steth',
    stakeTokenContractAddress: config.tokens.cvx,
    stakeTokenDecimals: 18,
    rewardTokenSymbol: 'CTR',
    rewardTokenDecimals: 18,
    zapTokens: [
      {
        symbol: 'cvx',
        icon: 'steth',
        address: config.tokens.cvx,
        needZap: false,
        isLp: true,
      }
    ],
  },
]
export default VAULT_LIST
